---
- name: Prep 
  hosts: localhost
  connection: local
  vars:
    become: yes
  tasks:
  - name: Install support packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - haproxy
      - httpd
      - httpd-tools
      - jq
      - vim-enhanced
    become_user: root
  - name: Install openshift installer utility
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes
  - name: Install OC utility
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
      dest: /usr/local/bin
